// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfCDIH9nxneDSJZzl_NeJ3XSByKEcV1bE',
    appId: '1:1012376722580:web:7457708f516fb0b24d2881',
    messagingSenderId: '1012376722580',
    projectId: 'erzurum-atlasi',
    authDomain: 'erzurum-atlasi.firebaseapp.com',
    storageBucket: 'erzurum-atlasi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuxOXM0xGQ0THwVnZ5v0NQmvsFAdG_hiw',
    appId: '1:1012376722580:android:d573da92dbae701b4d2881',
    messagingSenderId: '1012376722580',
    projectId: 'erzurum-atlasi',
    storageBucket: 'erzurum-atlasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1BEz_3hbvc9okAVTQ_T-NFB6y2Lojwi8',
    appId: '1:1012376722580:ios:d357c19427da25c54d2881',
    messagingSenderId: '1012376722580',
    projectId: 'erzurum-atlasi',
    storageBucket: 'erzurum-atlasi.firebasestorage.app',
    iosBundleId: 'com.example.erzurumAkilliSehirUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1BEz_3hbvc9okAVTQ_T-NFB6y2Lojwi8',
    appId: '1:1012376722580:ios:d357c19427da25c54d2881',
    messagingSenderId: '1012376722580',
    projectId: 'erzurum-atlasi',
    storageBucket: 'erzurum-atlasi.firebasestorage.app',
    iosBundleId: 'com.example.erzurumAkilliSehirUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfCDIH9nxneDSJZzl_NeJ3XSByKEcV1bE',
    appId: '1:1012376722580:web:a5fdd9f3260e65b44d2881',
    messagingSenderId: '1012376722580',
    projectId: 'erzurum-atlasi',
    authDomain: 'erzurum-atlasi.firebaseapp.com',
    storageBucket: 'erzurum-atlasi.firebasestorage.app',
  );
}
